version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: rwe
      POSTGRES_PASSWORD: rwe_dev_password
      POSTGRES_DB: rwe_platform
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U rwe']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  api:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.api
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgres://rwe:rwe_dev_password@postgres:5432/rwe_platform
      REDIS_URL: redis://redis:6379
    ports:
      - '4000:4000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  web:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.web
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  postgres_data:
